// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PremierNexus.DataAccess.Concrete;

#nullable disable

namespace PremierNexus.DataAccess.Migrations
{
    [DbContext(typeof(PremierNexusContext))]
    partial class PremierNexusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PremierNexus.Entities.Concrete.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeagueId"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeagueId");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<int?>("Attendance")
                        .HasColumnType("int");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int?>("AwayScoreHT")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScoreHT")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Referee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<short>("WeekNumber")
                        .HasColumnType("smallint");

                    b.HasKey("MatchId");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("StadiumId");

                    b.HasIndex("Status");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.MatchEvent", b =>
                {
                    b.Property<int>("MatchEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchEventId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("ExtraMinute")
                        .HasColumnType("tinyint");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<short>("Minute")
                        .HasColumnType("smallint");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("MatchEventId");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("MatchEvents");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.MatchStatistics", b =>
                {
                    b.Property<int>("MatchStatisticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchStatisticsId"));

                    b.Property<int?>("AwayCorners")
                        .HasColumnType("int");

                    b.Property<int?>("AwayFouls")
                        .HasColumnType("int");

                    b.Property<int?>("AwayOffsides")
                        .HasColumnType("int");

                    b.Property<byte?>("AwayPassAccuracyPct")
                        .HasColumnType("tinyint");

                    b.Property<int?>("AwayPasses")
                        .HasColumnType("int");

                    b.Property<byte?>("AwayPossessionPct")
                        .HasColumnType("tinyint");

                    b.Property<int?>("AwayRedCards")
                        .HasColumnType("int");

                    b.Property<int?>("AwayShots")
                        .HasColumnType("int");

                    b.Property<int?>("AwayShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int?>("AwayYellowCards")
                        .HasColumnType("int");

                    b.Property<int?>("HomeCorners")
                        .HasColumnType("int");

                    b.Property<int?>("HomeFouls")
                        .HasColumnType("int");

                    b.Property<int?>("HomeOffsides")
                        .HasColumnType("int");

                    b.Property<byte?>("HomePassAccuracyPct")
                        .HasColumnType("tinyint");

                    b.Property<int?>("HomePasses")
                        .HasColumnType("int");

                    b.Property<byte?>("HomePossessionPct")
                        .HasColumnType("tinyint");

                    b.Property<int?>("HomeRedCards")
                        .HasColumnType("int");

                    b.Property<int?>("HomeShots")
                        .HasColumnType("int");

                    b.Property<int?>("HomeShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int?>("HomeYellowCards")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.HasKey("MatchStatisticsId");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("MatchStatistics");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SeasonId");

                    b.HasIndex("LeagueId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.Stadium", b =>
                {
                    b.Property<int>("StadiumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StadiumId"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StadiumId");

                    b.ToTable("Stadiums");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Founded")
                        .HasColumnType("int");

                    b.Property<int?>("HomeStadiumId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.HasIndex("HomeStadiumId");

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.Match", b =>
                {
                    b.HasOne("PremierNexus.Entities.Concrete.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PremierNexus.Entities.Concrete.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PremierNexus.Entities.Concrete.Season", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PremierNexus.Entities.Concrete.Stadium", "Stadium")
                        .WithMany("Matches")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.MatchEvent", b =>
                {
                    b.HasOne("PremierNexus.Entities.Concrete.Match", "Match")
                        .WithMany("MatchEvents")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PremierNexus.Entities.Concrete.Team", "Team")
                        .WithMany("MatchEvents")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.MatchStatistics", b =>
                {
                    b.HasOne("PremierNexus.Entities.Concrete.Match", "Match")
                        .WithOne("MatchStatistics")
                        .HasForeignKey("PremierNexus.Entities.Concrete.MatchStatistics", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.Season", b =>
                {
                    b.HasOne("PremierNexus.Entities.Concrete.League", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.Team", b =>
                {
                    b.HasOne("PremierNexus.Entities.Concrete.Stadium", "HomeStadium")
                        .WithMany("TeamsWithHomeStadium")
                        .HasForeignKey("HomeStadiumId");

                    b.HasOne("PremierNexus.Entities.Concrete.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeStadium");

                    b.Navigation("League");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.League", b =>
                {
                    b.Navigation("Seasons");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.Match", b =>
                {
                    b.Navigation("MatchEvents");

                    b.Navigation("MatchStatistics")
                        .IsRequired();
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.Season", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.Stadium", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("TeamsWithHomeStadium");
                });

            modelBuilder.Entity("PremierNexus.Entities.Concrete.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("MatchEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
